### ISSUE TITLE
Import data-src pr into this extension

### ISSUE THREAD

**Issue by sebfie** [yireo/Yireo_NextGenImages#2]
Hello,

Thank you for this extension, 

Is it possible to have this code : https://github.com/yireo/Yireo_Webp2/pull/51/files

in this extension? 

Thank a lot !

**Comment by ikk0** [comment]
Yes, I agree this would be great.

**Comment by jissereitsma** [comment]
Thanks for pointing at this. The module is entirely refactored, so it is no longer the responsibility of the `Yireo_Webp2` module to apply the `data-src`. Instead, this should lie with the `Yireo_NextGenImages` module. While migrating this functionality, a couple of things fell of the wagon. But now, NextGenImages v0.0.6 should fix this. Let me know if this works for you.

https://github.com/yireo/Yireo_NextGenImages/releases/tag/0.0.6

**Comment by jissereitsma** [comment]
I'm closing this ticket because of inactivity, but let me know once there are issues.
