### ISSUE TITLE
how can i unistall it?

### ISSUE THREAD

**Issue by panteliskopsias** [yireo/Yireo_NextGenImages#27]
i run 
bin/magento module:uninstall Yireo_NextGenImages Yireo_Webp2
setup
compile
deploy 
and i get 
{"0":"The contents from the \"\/var\/www\/html\/code\/vendor\/yireo\/magento2-next-gen-images\/etc\/module.xml\" file can't be read. ....

**Comment by jissereitsma** [comment]
I'm not sure what you expect of `module:uninstall` but as you might have heard in other community channels, it is not written for any common deployment lines. Instead, remove the module from composer, because you can only install this module through composer. Next, wipe the cache, done.

**Comment by AreebKhan17** [comment]
composer remove yireo/magento2-next-gen-images
