### ISSUE TITLE
Gallery doesn't always show up in product view

### ISSUE THREAD

**Issue by interwijs** [yireo/Yireo_NextGenImages#32]
Hello Jisse,

We're having some troubles with this module in Magento 2.4.4 / php 8.1. The gallery in the product view doesn't always show up in the product view. It happens when the thumbs are not yet generated when visiting a product view. There are no errors in de logs.

**Comment by jissereitsma** [comment]
Could you try upgrading the WebP module to 0.12.1 and see if that works?

**Comment by interwijs** [comment]
Please explain what's changed in this version that solved the problem.

**Comment by jissereitsma** [comment]
Actually, for this there are CHANGELOGs and git commits: https://github.com/yireo/Yireo_Webp2/commit/32b13098b70baebbd35559b297f4ad559cdf0652 :)

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.
