### ISSUE TITLE
Fastly not loading image data into json

### ISSUE THREAD

**Issue by sunilit42** [yireo/Yireo_NextGenImages#35]
Hello

IN cloud, when we go from product list page to product page we are facing issue

```
<type name="Magento\Catalog\Block\Product\View\Gallery">
        <plugin name="Yireo_NextGenImages::addImagesToGalleryImagesJson" type="Yireo\NextGenImages\Plugin\AddImagesToGalleryImagesJson"/>
    </type>
    
```

this plugin not working that time, but when i append something into url then refresh (fresh) then works fine

**Comment by sunilit42** [comment]
Hello,

When we go product list to pdp >> some how Yireo_NextGenImages plugin is not calling so json is not creating with webp images

so webp image is not calling on that page

But if i m opening same url with ?v=11 json is creating with proper webp image

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.
