### ISSUE TITLE
Bug: Multiple images with same img-Tag content

### ISSUE THREAD

**Issue by tim-breitenstein-it** [yireo/Yireo_NextGenImages#50]
If we have, for example a list of attachments and file type symbol with always the same `<img ...>` content, the `str_replace` functions inside the `addImageMarkersToHtml` replaces the `<img ...>`-Marker multiple times!

![image](https://user-images.githubusercontent.com/65597245/203789350-7e310218-c378-4007-a03e-d49c7a540a0d.png)

Result in:

![image](https://user-images.githubusercontent.com/65597245/203790987-b54e21de-7890-41a7-9a83-8191e990c33e.png)

[addImageMarkersToHtml](https://github.com/yireo/Yireo_NextGenImages/blob/master/Util/HtmlReplacer.php#L148):
```
   /**
     * @param string $html
     * @return string
     */
    private function addImageMarkersToHtml(string $html): string
    {
        if (preg_match_all('/<img([^\>]+)>/mi', $html, $imgMatches)) {
            $i = 1;
            foreach ($imgMatches[0] as $imgMatch) {
                $newTag = str_replace('<img ', '<img ' . self::MARKER_CODE . '="' . $i . '" ', $imgMatch);
                $html = str_replace($imgMatch, $newTag, $html);
                $i++;

            }
        }

        return $html;
    }
```

Works (only replace first occurrence):
```
   /**
     * @param string $html
     * @return string
     */
    private function addImageMarkersToHtml(string $html): string
    {
        if (preg_match_all('/<img([^\>]+)>/mi', $html, $imgMatches)) {
            $i = 1;
            foreach ($imgMatches[0] as $imgMatch) {
                $newTag = str_replace('<img ', '<img ' . self::MARKER_CODE . '="' . $i . '" ', $imgMatch);
                $pos = strpos($html, $imgMatch);
                if ($pos !== false) {
                    $html = substr_replace($html, $newTag, $pos, strlen($imgMatch));
                }
                $i++;

            }
        }

        return $html;
    }
```

**Comment by RetroProgrammist** [comment]
Hello, i have same problem, fixed it in HtmlReplacer::isAllowedByNextTag method 
```
    /**
     * @param string $nextTag
     * @return bool
     */
    private function isAllowedByNextTag(string $nextTag): bool //input like </TagName (e.g. </picture, </div, </a)
    {
        if ($nextTag === '/picture' || $nextTag === '/source') { //</picture !== /picture
            return false;
        }

        return true;
    }
```
Need change \Yireo\NextGenImages\Util\HtmlReplacer::97 string like below:
`  if ($nextTag === '</picture' || $nextTag === '</source')`

**Comment by RetroProgrammist** [comment]
Hello, i have same problem with multiply same img on my pages (etc. logo, labels or "No Image" plug) 
My fix: 
```
    private function addImageMarkersToHtml(string $html): string
    {
        $i = 0;
        $html = preg_replace_callback(
            "/<img([^\>]+)>/mi",
            function ($matches) use (&$i) {
                $i += 1;
                return str_replace('<img ', '<img ' . self::MARKER_CODE . '="' . $i . '" ', $matches[0]);
            },
            $html);

        return $html;
    }
```

My fork commit https://github.com/RetroProgrammist/Yireo_NextGenImages/commit/36e973d29d6856773f808b942cbc26e264d6576a

**Comment by jissereitsma** [comment]
Thanks for keeping this alive. I was occupied for quite some time, but also wanted to fix this only if it was reproducable and testable (for quality purposes). I've added an integration test that proves this bug. And then again thanks to the PR of @RetroProgrammist this bug is fixed. Thanks @RetroProgrammist !

**Comment by jissereitsma** [comment]
I'll keep this issue open until it is reported back that this bug is indeed fixed.

**Comment by tim-breitenstein-it** [comment]
> Hello, i have same problem with multiply same img on my pages (etc. logo, labels or "No Image" plug) My fix:
> 
> ```
>     private function addImageMarkersToHtml(string $html): string
>     {
>         $i = 0;
>         $html = preg_replace_callback(
>             "/<img([^\>]+)>/mi",
>             function ($matches) use (&$i) {
>                 $i += 1;
>                 return str_replace('<img ', '<img ' . self::MARKER_CODE . '="' . $i . '" ', $matches[0]);
>             },
>             $html);
> 
>         return $html;
>     }
> ```
> 
> My fork commit [RetroProgrammist@36e973d](https://github.com/RetroProgrammist/Yireo_NextGenImages/commit/36e973d29d6856773f808b942cbc26e264d6576a)

Works fine for me!

**Comment by RetroProgrammist** [comment]
Hello, i found some example where it doesn't work 
If we have img tag like: <img[\s]+[^\>]+> - looks like this template. 
Then `str_replace('<img ', '<img ' . self::MARKER_CODE . '="' . $i . '" ', $matches[0]);` does not work but in html all looks fine
Pay attention

**Comment by jissereitsma** [comment]
Sorry for a long delay. I simply overlooked this. The fix @RetroProgrammist seemed to suggest to me, is now part of the latest release.
