### ISSUE TITLE
Warning: DOMDocument::loadHTML(): Empty string supplied as input

### ISSUE THREAD

**Issue by marcinfr** [yireo/Yireo_NextGenImages#51]
Hi,

Some of controllers can return empty string as html, for example:
review/product/listAjax

In this case we have error 500 with error log: DOMDocument::loadHTML(): Empty string supplied as input.

I have fixed it in my project by plugin:

    public function aroundReplace(\Yireo\NextGenImages\Util\HtmlReplacer $htmlReplacer, callable $proceed, string $html): string
    {
        if ($html) {
            $html = $proceed($html);
        }

        return $html;
    }

**Comment by marcinfr** [comment]
Now i see that its fixed in latest version.
Thank You for Your work!

**Comment by jissereitsma** [comment]
:)
