### ISSUE TITLE
Comparing the URL in getFilenameFromUrl() doesn't work, because normalizeUrl() changes https to http

### ISSUE THREAD

**Issue by jeroen-dhm** [yireo/Yireo_NextGenImages#63]
I just noticed an issue with one of your clients' stores using NextGenImages where the images didn't get replaced. Upon debugging I noticed that the `getFilenameFromUrl()` method in `Yireo\NextGenImages\Util\UrlConvertor` and the `isLocal()` method in the same class try to compare the URL with https to a URL without https.

This happens because of the call to `normalizeUrl()` on lines 64 and 132. The `normalizeUrl()` method replaces https to http, which invalidates the check.

The check results in an `NotFoundException` exception with the message "URL $url does not appear to be a local file" (line 135).

**Comment by jissereitsma** [comment]
Thanks for posting this. Indeed I'm noticing the same since the last release. A new version 0.3.19 is underway to fix this.

**Comment by jissereitsma** [comment]
Version 0.4.0 has now been released with a fix on board for this issue.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.
