### ISSUE TITLE
Bug: fetchpriority="high" has no effect

### ISSUE THREAD

**Issue by Hoargarth** [yireo/Yireo_NextGenImages#64]
Version: `0.4.0`
Feature: Disable lazyloading with `fetchpriority="high"`

Expected behaviour:
Adding `fetchpriority="high"` to an image, will prevent adding `loading="lazy"` to the output image

Actual behaviour:
Adding `fetchpriority="high"` doesn't do anything

Solution:
The `preg_replace` which adds lazyloading is done before the check for an existing `fetchpriority="high"`.
https://github.com/yireo/Yireo_NextGenImages/blob/master/view/frontend/templates/picture.phtml#L12
Line 12 should be moved ater the condition in line 19

Related issue:  https://github.com/yireo/Yireo_NextGenImages/issues/52

**Comment by Hoargarth** [comment]
PR for this☝🏻

**Comment by jissereitsma** [comment]
Update, a fix is underway already. I hope to release things today.

**Comment by jissereitsma** [comment]
I'm closing this ticket, because it should already be fixed.
