### ISSUE TITLE
Next Gen Images can't be disabled by website scope

### ISSUE THREAD

**Issue by mgroensmit** [yireo/Yireo_NextGenImages#7]
It is possible to set the yireo_nextgenimages/settings/enabled config value on website scope, the Yireo\NextGenImages\Config\Config class only ever reads the config value from the default scope though, so you can't enable/disable the module's functionality for specific websites.

**Comment by jissereitsma** [comment]
Thanks for noticing. This will be fixed in version 0.10.10 to be released still today.

**Comment by jissereitsma** [comment]
Closing this issue because it is fixed already.
