### ISSUE TITLE
Error after upgrading to latest version(s)

### ISSUE THREAD

**Issue by onlinemusketeers** [yireo/Yireo_NextGenImages#70]
Hi Jisse,

I get a conflict after updating the extensions.  Any thoughts about what could have go wrong?
Tnx!

1 exception(s):
Exception #0 (Exception): Warning: 
Declaration of 

Hyva\YireoNextGenImages\Model\AlpinePictureFactory::create(Yireo\NextGenImages\Image\Image $originalImage, array $images, string $htmlTag, bool $isDataSrc = false): Yireo\NextGenImages\Block\Picture 

should be compatible with 

Yireo\NextGenImages\Block\PictureFactory::create(Yireo\NextGenImages\Image\Image $originalImage, array $images, string $htmlTag, string $srcAttribute = 'src'): Yireo\NextGenImages\Block\Picture in /magento/vendor/hyva-themes/magento2-yireo-next-gen-images/src/Model/AlpinePictureFactory.php on line 57

**Comment by jissereitsma** [comment]
Did you make sure to remove the Hyva compatibility module, because the main reason for upgrading is that compabitility is built into the core module already?

**Comment by onlinemusketeers** [comment]
That did the job! Thanks a lot Jisse!
