### ISSUE TITLE
Command `next-gen-images:convert` not working if images are on shared folders

### ISSUE THREAD

**Issue by wilfriedwolf** [yireo/Yireo_NextGenImages#80]
Hi!

I just was trying to convert some images with your command and it failed with the error message:

```
In UrlConvertor.php line 112:
                                                                                                                             
  Filename "..../shared/pub/media/wysiwyg/Inhaltsseiten/federweisser.jpg" is not matched with an URL  
```

This is because the `media`-folder is shared and the realpath of the file is taken but not from the paths.

I'll do a quick PR.

Best regards,

Willi

**Comment by jissereitsma** [comment]
I think this issue can be closed.
