### ISSUE TITLE
HtmlReplacer fails if img attribute contains >

### ISSUE THREAD

**Issue by wilfriedwolf** [yireo/Yireo_NextGenImages#82]
Hi there,

we have a theme where the gallery image tags contain an attribute like 

`@click="fullscreen = true; $nextTick(() => calcPageSize())"`

when trying to use your module, this yields in broken html, since the  HtmlReplacer uses this angle bracket as tag delimiter.

Just wrote a fix, so if you can check and maybe merge.

Best regards,

Willi

**Comment by jissereitsma** [comment]
Thanks for the PR. It looks great. 

As a (major) side note: The Alpine snippet you posted is 0% CSP compliant, so as soon you upgrade to a Hyva CSP build (with CSP and PCI Compliance having a deadline of July 2025), this will break.

I'm happy to include the fix nonetheless ;)

**Comment by wilfriedwolf** [comment]
Ooops. Well, I didn't write it, more of a backender. I'll check with my colleagues. Best regards.

Willi

**Comment by jissereitsma** [comment]
No worries. I'm closing this ticket as of yet. If something is wrong, feel free to reopen.
